package Leetcode;

import java.util.Arrays;
import java.util.HashMap;

/*Given two strings s and t which consist of only lowercase letters.

String t is generated by random shuffling string s and then add one more letter at a random position.

Find the letter that was added in t.*/
public class FindStringDifference {
	public static void main(String[] args) {
		String s = "abcd", t = "abcde";
		System.out.println(findTheDifference(s, t));
	}

	static char findTheDifference(String s, String t) {
		char[] schar = s.toCharArray();
		char[] tchar = t.toCharArray();
		int[] in = new int[50];
		for (char a : schar)
			in[a-'a']++;
		for (char a : tchar)
			in[a-'a']--;
		
		for (int i=0; i<in.length; i++)
			if (in[i] != 0)
				return (char) ('a'+i);
		return 0;
	}
}
